<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_header_email_or_phone_confirmation</name>
   <tag></tag>
   <elementGuidId>e57db199-51f5-4557-8f3d-50828cf92d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.uiHeaderTitle</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
